### ISSUE TITLE
I want to a build guide

### ISSUE THREAD

**Issue by linuxias** [nnstreamer/nnstreamer-edge#156]
Hello,

I am very interested in OnDeviceAI and would like to participate in this project. 
I am wondering if you could provide a build guide and how to run test in local environment.

Thanks and Regards

**Comment by gichan-jang** [comment]
Hello @linuxias, I'll write a quick start guide and upload it. Thank you for your interest in this project.

**Comment by linuxias** [comment]
Hello, @gichan-jang 

Thank you for your response.

I want to contribute to the development of the nnstreamer-edge project. 
However, I asked because I didn't have any information such as target board or build method yet.

It would be great if the guide could be supported as soon as possible. 

Thank you.

**Comment by gichan-jang** [comment]
@linuxias, Please refer [this](https://github.com/nnstreamer/nnstreamer-edge#quick-start-guide-for-nnstreamer-edge-ubuntu-2004-lts-or-2204-lts)

**Comment by linuxias** [comment]
> @linuxias, Please refer [this](https://github.com/nnstreamer/nnstreamer-edge#quick-start-guide-for-nnstreamer-edge-ubuntu-2004-lts-or-2204-lts)

Wow, it's good news to me!!
I hope, I can contribute to this project through this guide!
Thanks and Regards.
